### ISSUE TITLE
Add practical 2

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/TDStests#14]

**Comment by yyuanxuan** [comment]
The branch (_add-p2_) has been created, and Practical 2 (p2/index.qmd) has been tested and pushed to the branch.

**Comment by Robinlovelace** [comment]
Great, thank @yyuanxuan. Next step: open a Pull Request. You can do that in the web app (search online for details) or, IMO even better, with the `gh` CLI tool with the following command in the system shell:

```
gh pr create
```

See details here: https://cli.github.com/manual/gh_pr_create

**Comment by Robinlovelace** [comment]
Looking good: https://itsleeds.github.io/TDStests/p2/
