### ISSUE TITLE
Check main branch rules

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/TDStests#26]
I've tried to prohibit pushing to main without a PR, does it work? Please test at some point @yyuanxuan and let me know, e.g. by making a 1-line change to README.qmd and trying 

```
git push
```

on the main branch, which you get get onto with

```
git checkout main
git pull # check it's up-to-date
```

**Comment by yyuanxuan** [comment]
I just tried this and received the following message, which is a good sign:
! [remote rejected] main -> main (push declined due to repository rule violations)”

**Comment by Robinlovelace** [comment]
Awesome, thanks for testing it!

As a next stage, could you try pushing to a branch, e.g. with the following:

```shell
gh issue develop 26 --checkout
# make a minimal change
git commit -am 'Test change'
git push
gh pr create
```
