### ISSUE TITLE
Where to put course materials

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/TDStests#8]
Currently we have the following in the schedule, with hyperlinks to non-existent locations:

![image](https://github.com/user-attachments/assets/8f5ddce4-1660-4cbc-bc27-9ea4d74bbba9)

Source: https://itsleeds.github.io/TDStests/schedule.html

Eventually there should I think be 2 (maybe 3) links for each session:

- Slides
- Materials (including reading material)
- (Possibly) homework or something else

In terms of Quarto website design I think it would make most sense to put the content in:

```
/slides/01.qmd
```

or the name of the slides, e.g.

```
slides/intro.qmd
```

Having both number of the session and the name is unhelpful I think. We can do the same for materials.

Thoughts welcome, cc @rogerbeecham, @mem48, @yyuanxuan, @eugenividal what do you think would work best?

**Comment by mem48** [comment]
Were are required to put course material on Minerva, I seems confusing to put things in other places too

**Comment by Robinlovelace** [comment]
Going for something like this: https://www.roger-beecham.com/comp-sds/

If we use GitHub for sure we're going to have at least 2 places, and removing GitHub isn't on the table.

It's more about making the content already on GitHub a bit more organised.

**Comment by Robinlovelace** [comment]
p1, p2, p3 etc in course folder is simple and good, going with that for now.
